# This Makefile is for the Font::TTF extension to perl.
#
# It was generated automatically by MakeMaker version
# 7.24 (Revision: 72400) from the contents of
# Makefile.PL. Don't edit this file, edit Makefile.PL instead.
#
#       ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker ARGV: (q[INSTALL_BASE=/home/barry/perl5], q[LIB=/home/barry/Desktop/Owen_Donohue/mirdeep2/mirdeep2-master/lib/perl5])
#

#   MakeMaker Parameters:

#     ABSTRACT => q[TTF font support for Perl]
#     AUTHOR => [q[martin_hosken@sil.org]]
#     BUILD_REQUIRES => {  }
#     CONFIGURE_REQUIRES => {  }
#     LICENSE => q[artistic_2]
#     NAME => q[Font::TTF]
#     PREREQ_PM => { IO::String=>q[0] }
#     TEST_REQUIRES => {  }
#     VERSION_FROM => q[lib/Font/TTF.pm]

# --- MakeMaker post_initialize section:


# --- MakeMaker const_config section:

# These definitions are from config.sh (via /usr/lib/x86_64-linux-gnu/perl/5.26/Config.pm).
# They may have been overridden via Makefile.PL or on the command line.
AR = ar
CC = x86_64-linux-gnu-gcc
CCCDLFLAGS = -fPIC
CCDLFLAGS = -Wl,-E
DLEXT = so
DLSRC = dl_dlopen.xs
EXE_EXT = 
FULL_AR = /usr/bin/ar
LD = x86_64-linux-gnu-gcc
LDDLFLAGS = -shared -L/usr/local/lib -fstack-protector-strong
LDFLAGS =  -fstack-protector-strong -L/usr/local/lib
LIBC = libc-2.27.so
LIB_EXT = .a
OBJ_EXT = .o
OSNAME = linux
OSVERS = 4.9.0
RANLIB = :
SITELIBEXP = /usr/local/share/perl/5.26.1
SITEARCHEXP = /usr/local/lib/x86_64-linux-gnu/perl/5.26.1
SO = so
VENDORARCHEXP = /usr/lib/x86_64-linux-gnu/perl5/5.26
VENDORLIBEXP = /usr/share/perl5


# --- MakeMaker constants section:
AR_STATIC_ARGS = cr
DIRFILESEP = /
DFSEP = $(DIRFILESEP)
NAME = Font::TTF
NAME_SYM = Font_TTF
VERSION = 1.05
VERSION_MACRO = VERSION
VERSION_SYM = 1_05
DEFINE_VERSION = -D$(VERSION_MACRO)=\"$(VERSION)\"
XS_VERSION = 1.05
XS_VERSION_MACRO = XS_VERSION
XS_DEFINE_VERSION = -D$(XS_VERSION_MACRO)=\"$(XS_VERSION)\"
INST_ARCHLIB = blib/arch
INST_SCRIPT = blib/script
INST_BIN = blib/bin
INST_LIB = blib/lib
INST_MAN1DIR = blib/man1
INST_MAN3DIR = blib/man3
MAN1EXT = 1p
MAN3EXT = 3pm
INSTALLDIRS = site
INSTALL_BASE = /home/barry/Desktop/Owen_Donohue/mirdeep2/mirdeep2-master
DESTDIR = 
PREFIX = $(INSTALL_BASE)
INSTALLPRIVLIB = $(INSTALL_BASE)/lib/perl5
DESTINSTALLPRIVLIB = $(DESTDIR)$(INSTALLPRIVLIB)
INSTALLSITELIB = $(INSTALL_BASE)/lib/perl5
DESTINSTALLSITELIB = $(DESTDIR)$(INSTALLSITELIB)
INSTALLVENDORLIB = $(INSTALL_BASE)/lib/perl5
DESTINSTALLVENDORLIB = $(DESTDIR)$(INSTALLVENDORLIB)
INSTALLARCHLIB = $(INSTALL_BASE)/lib/perl5/x86_64-linux-gnu-thread-multi
DESTINSTALLARCHLIB = $(DESTDIR)$(INSTALLARCHLIB)
INSTALLSITEARCH = $(INSTALL_BASE)/lib/perl5/x86_64-linux-gnu-thread-multi
DESTINSTALLSITEARCH = $(DESTDIR)$(INSTALLSITEARCH)
INSTALLVENDORARCH = $(INSTALL_BASE)/lib/perl5/x86_64-linux-gnu-thread-multi
DESTINSTALLVENDORARCH = $(DESTDIR)$(INSTALLVENDORARCH)
INSTALLBIN = $(INSTALL_BASE)/bin
DESTINSTALLBIN = $(DESTDIR)$(INSTALLBIN)
INSTALLSITEBIN = $(INSTALL_BASE)/bin
DESTINSTALLSITEBIN = $(DESTDIR)$(INSTALLSITEBIN)
INSTALLVENDORBIN = $(INSTALL_BASE)/bin
DESTINSTALLVENDORBIN = $(DESTDIR)$(INSTALLVENDORBIN)
INSTALLSCRIPT = $(INSTALL_BASE)/bin
DESTINSTALLSCRIPT = $(DESTDIR)$(INSTALLSCRIPT)
INSTALLSITESCRIPT = $(INSTALL_BASE)/bin
DESTINSTALLSITESCRIPT = $(DESTDIR)$(INSTALLSITESCRIPT)
INSTALLVENDORSCRIPT = $(INSTALL_BASE)/bin
DESTINSTALLVENDORSCRIPT = $(DESTDIR)$(INSTALLVENDORSCRIPT)
INSTALLMAN1DIR = $(INSTALL_BASE)/man/man1
DESTINSTALLMAN1DIR = $(DESTDIR)$(INSTALLMAN1DIR)
INSTALLSITEMAN1DIR = $(INSTALL_BASE)/man/man1
DESTINSTALLSITEMAN1DIR = $(DESTDIR)$(INSTALLSITEMAN1DIR)
INSTALLVENDORMAN1DIR = $(INSTALL_BASE)/man/man1
DESTINSTALLVENDORMAN1DIR = $(DESTDIR)$(INSTALLVENDORMAN1DIR)
INSTALLMAN3DIR = $(INSTALL_BASE)/man/man3
DESTINSTALLMAN3DIR = $(DESTDIR)$(INSTALLMAN3DIR)
INSTALLSITEMAN3DIR = $(INSTALL_BASE)/man/man3
DESTINSTALLSITEMAN3DIR = $(DESTDIR)$(INSTALLSITEMAN3DIR)
INSTALLVENDORMAN3DIR = $(INSTALL_BASE)/man/man3
DESTINSTALLVENDORMAN3DIR = $(DESTDIR)$(INSTALLVENDORMAN3DIR)
PERL_LIB = /usr/share/perl/5.26
PERL_ARCHLIB = /usr/lib/x86_64-linux-gnu/perl/5.26
PERL_ARCHLIBDEP = /usr/lib/x86_64-linux-gnu/perl/5.26
LIBPERL_A = libperl.a
FIRST_MAKEFILE = Makefile
MAKEFILE_OLD = Makefile.old
MAKE_APERL_FILE = Makefile.aperl
PERLMAINCC = $(CC)
PERL_INC = /usr/lib/x86_64-linux-gnu/perl/5.26/CORE
PERL_INCDEP = /usr/lib/x86_64-linux-gnu/perl/5.26/CORE
PERL = "/usr/bin/perl"
FULLPERL = "/usr/bin/perl"
ABSPERL = $(PERL)
PERLRUN = $(PERL)
FULLPERLRUN = $(FULLPERL)
ABSPERLRUN = $(ABSPERL)
PERLRUNINST = $(PERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
FULLPERLRUNINST = $(FULLPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
ABSPERLRUNINST = $(ABSPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
PERL_CORE = 0
PERM_DIR = 755
PERM_RW = 644
PERM_RWX = 755

MAKEMAKER   = /usr/share/perl/5.26/ExtUtils/MakeMaker.pm
MM_VERSION  = 7.24
MM_REVISION = 72400

# FULLEXT = Pathname for extension directory (eg Foo/Bar/Oracle).
# BASEEXT = Basename part of FULLEXT. May be just equal FULLEXT. (eg Oracle)
# PARENT_NAME = NAME without BASEEXT and no trailing :: (eg Foo::Bar)
# DLBASE  = Basename part of dynamic library. May be just equal BASEEXT.
MAKE = make
FULLEXT = Font/TTF
BASEEXT = TTF
PARENT_NAME = Font
DLBASE = $(BASEEXT)
VERSION_FROM = lib/Font/TTF.pm
OBJECT = 
LDFROM = $(OBJECT)
LINKTYPE = dynamic
BOOTDEP = 

# Handy lists of source code files:
XS_FILES = 
C_FILES  = 
O_FILES  = 
H_FILES  = 
MAN1PODS = 
MAN3PODS = lib/Font/TTF.pm \
	lib/Font/TTF/AATKern.pm \
	lib/Font/TTF/AATutils.pm \
	lib/Font/TTF/Anchor.pm \
	lib/Font/TTF/Bsln.pm \
	lib/Font/TTF/Cmap.pm \
	lib/Font/TTF/Coverage.pm \
	lib/Font/TTF/Cvt_.pm \
	lib/Font/TTF/DSIG.pm \
	lib/Font/TTF/Delta.pm \
	lib/Font/TTF/Dumper.pm \
	lib/Font/TTF/EBDT.pm \
	lib/Font/TTF/EBLC.pm \
	lib/Font/TTF/Fdsc.pm \
	lib/Font/TTF/Feat.pm \
	lib/Font/TTF/Features/Cvar.pm \
	lib/Font/TTF/Features/Size.pm \
	lib/Font/TTF/Features/Sset.pm \
	lib/Font/TTF/Fmtx.pm \
	lib/Font/TTF/Font.pm \
	lib/Font/TTF/Fpgm.pm \
	lib/Font/TTF/GDEF.pm \
	lib/Font/TTF/GPOS.pm \
	lib/Font/TTF/GSUB.pm \
	lib/Font/TTF/Glat.pm \
	lib/Font/TTF/Gloc.pm \
	lib/Font/TTF/Glyf.pm \
	lib/Font/TTF/Glyph.pm \
	lib/Font/TTF/GrFeat.pm \
	lib/Font/TTF/Hdmx.pm \
	lib/Font/TTF/Head.pm \
	lib/Font/TTF/Hhea.pm \
	lib/Font/TTF/Hmtx.pm \
	lib/Font/TTF/Kern.pm \
	lib/Font/TTF/Kern/ClassArray.pm \
	lib/Font/TTF/Kern/CompactClassArray.pm \
	lib/Font/TTF/Kern/OrderedList.pm \
	lib/Font/TTF/Kern/StateTable.pm \
	lib/Font/TTF/Kern/Subtable.pm \
	lib/Font/TTF/LTSH.pm \
	lib/Font/TTF/Loca.pm \
	lib/Font/TTF/Manual.pod \
	lib/Font/TTF/Maxp.pm \
	lib/Font/TTF/Mort.pm \
	lib/Font/TTF/Mort/Chain.pm \
	lib/Font/TTF/Mort/Contextual.pm \
	lib/Font/TTF/Mort/Insertion.pm \
	lib/Font/TTF/Mort/Ligature.pm \
	lib/Font/TTF/Mort/Noncontextual.pm \
	lib/Font/TTF/Mort/Rearrangement.pm \
	lib/Font/TTF/Mort/Subtable.pm \
	lib/Font/TTF/Name.pm \
	lib/Font/TTF/OS_2.pm \
	lib/Font/TTF/OTTags.pm \
	lib/Font/TTF/OldCmap.pm \
	lib/Font/TTF/OldMort.pm \
	lib/Font/TTF/PCLT.pm \
	lib/Font/TTF/PSNames.pm \
	lib/Font/TTF/Post.pm \
	lib/Font/TTF/Prep.pm \
	lib/Font/TTF/Prop.pm \
	lib/Font/TTF/Segarr.pm \
	lib/Font/TTF/Silf.pm \
	lib/Font/TTF/Sill.pm \
	lib/Font/TTF/Table.pm \
	lib/Font/TTF/Ttc.pm \
	lib/Font/TTF/Ttopen.pm \
	lib/Font/TTF/Useall.pm \
	lib/Font/TTF/Utils.pm \
	lib/Font/TTF/Vhea.pm \
	lib/Font/TTF/Vmtx.pm \
	lib/Font/TTF/Win32.pm \
	lib/Font/TTF/Woff.pm \
	lib/Font/TTF/Woff/MetaData.pm \
	lib/Font/TTF/Woff/PrivateData.pm \
	lib/Font/TTF/XMLparse.pm \
	lib/ttfmod.pl

# Where is the Config information that we are using/depend on
CONFIGDEP = $(PERL_ARCHLIBDEP)$(DFSEP)Config.pm $(PERL_INCDEP)$(DFSEP)config.h

# Where to build things
INST_LIBDIR      = $(INST_LIB)/Font
INST_ARCHLIBDIR  = $(INST_ARCHLIB)/Font

INST_AUTODIR     = $(INST_LIB)/auto/$(FULLEXT)
INST_ARCHAUTODIR = $(INST_ARCHLIB)/auto/$(FULLEXT)

INST_STATIC      = 
INST_DYNAMIC     = 
INST_BOOT        = 

# Extra linker info
EXPORT_LIST        = 
PERL_ARCHIVE       = 
PERL_ARCHIVEDEP    = 
PERL_ARCHIVE_AFTER = 


TO_INST_PM = lib/Font/TTF.pm \
	lib/Font/TTF/AATKern.pm \
	lib/Font/TTF/AATutils.pm \
	lib/Font/TTF/Anchor.pm \
	lib/Font/TTF/Bsln.pm \
	lib/Font/TTF/Changes_old.txt \
	lib/Font/TTF/Cmap.pm \
	lib/Font/TTF/Coverage.pm \
	lib/Font/TTF/Cvt_.pm \
	lib/Font/TTF/DSIG.pm \
	lib/Font/TTF/Delta.pm \
	lib/Font/TTF/Dumper.pm \
	lib/Font/TTF/EBDT.pm \
	lib/Font/TTF/EBLC.pm \
	lib/Font/TTF/Fdsc.pm \
	lib/Font/TTF/Feat.pm \
	lib/Font/TTF/Features/Cvar.pm \
	lib/Font/TTF/Features/Size.pm \
	lib/Font/TTF/Features/Sset.pm \
	lib/Font/TTF/Fmtx.pm \
	lib/Font/TTF/Font.pm \
	lib/Font/TTF/Fpgm.pm \
	lib/Font/TTF/GDEF.pm \
	lib/Font/TTF/GPOS.pm \
	lib/Font/TTF/GSUB.pm \
	lib/Font/TTF/Glat.pm \
	lib/Font/TTF/Gloc.pm \
	lib/Font/TTF/Glyf.pm \
	lib/Font/TTF/Glyph.pm \
	lib/Font/TTF/GrFeat.pm \
	lib/Font/TTF/Hdmx.pm \
	lib/Font/TTF/Head.pm \
	lib/Font/TTF/Hhea.pm \
	lib/Font/TTF/Hmtx.pm \
	lib/Font/TTF/Kern.pm \
	lib/Font/TTF/Kern/ClassArray.pm \
	lib/Font/TTF/Kern/CompactClassArray.pm \
	lib/Font/TTF/Kern/OrderedList.pm \
	lib/Font/TTF/Kern/StateTable.pm \
	lib/Font/TTF/Kern/Subtable.pm \
	lib/Font/TTF/LTSH.pm \
	lib/Font/TTF/Loca.pm \
	lib/Font/TTF/Manual.pod \
	lib/Font/TTF/Maxp.pm \
	lib/Font/TTF/Mort.pm \
	lib/Font/TTF/Mort/Chain.pm \
	lib/Font/TTF/Mort/Contextual.pm \
	lib/Font/TTF/Mort/Insertion.pm \
	lib/Font/TTF/Mort/Ligature.pm \
	lib/Font/TTF/Mort/Noncontextual.pm \
	lib/Font/TTF/Mort/Rearrangement.pm \
	lib/Font/TTF/Mort/Subtable.pm \
	lib/Font/TTF/Name.pm \
	lib/Font/TTF/OS_2.pm \
	lib/Font/TTF/OTTags.pm \
	lib/Font/TTF/OldCmap.pm \
	lib/Font/TTF/OldMort.pm \
	lib/Font/TTF/PCLT.pm \
	lib/Font/TTF/PSNames.pm \
	lib/Font/TTF/Post.pm \
	lib/Font/TTF/Prep.pm \
	lib/Font/TTF/Prop.pm \
	lib/Font/TTF/Segarr.pm \
	lib/Font/TTF/Silf.pm \
	lib/Font/TTF/Sill.pm \
	lib/Font/TTF/Table.pm \
	lib/Font/TTF/Ttc.pm \
	lib/Font/TTF/Ttopen.pm \
	lib/Font/TTF/Useall.pm \
	lib/Font/TTF/Utils.pm \
	lib/Font/TTF/Vhea.pm \
	lib/Font/TTF/Vmtx.pm \
	lib/Font/TTF/Win32.pm \
	lib/Font/TTF/Woff.pm \
	lib/Font/TTF/Woff/MetaData.pm \
	lib/Font/TTF/Woff/PrivateData.pm \
	lib/Font/TTF/XMLparse.pm \
	lib/ttfmod.pl


# --- MakeMaker platform_constants section:
MM_Unix_VERSION = 7.24
PERL_MALLOC_DEF = -DPERL_EXTMALLOC_DEF -Dmalloc=Perl_malloc -Dfree=Perl_mfree -Drealloc=Perl_realloc -Dcalloc=Perl_calloc


# --- MakeMaker tool_autosplit section:
# Usage: $(AUTOSPLITFILE) FileToSplit AutoDirToSplitInto
AUTOSPLITFILE = $(ABSPERLRUN)  -e 'use AutoSplit;  autosplit($$$$ARGV[0], $$$$ARGV[1], 0, 1, 1)' --



# --- MakeMaker tool_xsubpp section:


# --- MakeMaker tools_other section:
SHELL = /bin/sh
CHMOD = chmod
CP = cp
MV = mv
NOOP = $(TRUE)
NOECHO = @
RM_F = rm -f
RM_RF = rm -rf
TEST_F = test -f
TOUCH = touch
UMASK_NULL = umask 0
DEV_NULL = > /dev/null 2>&1
MKPATH = $(ABSPERLRUN) -MExtUtils::Command -e 'mkpath' --
EQUALIZE_TIMESTAMP = $(ABSPERLRUN) -MExtUtils::Command -e 'eqtime' --
FALSE = false
TRUE = true
ECHO = echo
ECHO_N = echo -n
UNINST = 0
VERBINST = 0
MOD_INSTALL = $(ABSPERLRUN) -MExtUtils::Install -e 'install([ from_to => {@ARGV}, verbose => '\''$(VERBINST)'\'', uninstall_shadows => '\''$(UNINST)'\'', dir_mode => '\''$(PERM_DIR)'\'' ]);' --
DOC_INSTALL = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'perllocal_install' --
UNINSTALL = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'uninstall' --
WARN_IF_OLD_PACKLIST = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'warn_if_old_packlist' --
MACROSTART = 
MACROEND = 
USEMAKEFILE = -f
FIXIN = $(ABSPERLRUN) -MExtUtils::MY -e 'MY->fixin(shift)' --
CP_NONEMPTY = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'cp_nonempty' --


# --- MakeMaker makemakerdflt section:
makemakerdflt : all
	$(NOECHO) $(NOOP)


# --- MakeMaker dist section:
TAR = tar
TARFLAGS = cvf
ZIP = zip
ZIPFLAGS = -r
COMPRESS = gzip --best
SUFFIX = .gz
SHAR = shar
PREOP = $(NOECHO) $(NOOP)
POSTOP = $(NOECHO) $(NOOP)
TO_UNIX = $(NOECHO) $(NOOP)
CI = ci -u
RCS_LABEL = rcs -Nv$(VERSION_SYM): -q
DIST_CP = best
DIST_DEFAULT = tardist
DISTNAME = Font-TTF
DISTVNAME = Font-TTF-1.05


# --- MakeMaker macro section:


# --- MakeMaker depend section:


# --- MakeMaker cflags section:


# --- MakeMaker const_loadlibs section:


# --- MakeMaker const_cccmd section:


# --- MakeMaker post_constants section:


# --- MakeMaker pasthru section:

PASTHRU = LIB="$(LIB)"\
	LIBPERL_A="$(LIBPERL_A)"\
	LINKTYPE="$(LINKTYPE)"\
	LD="$(LD)"\
	PREFIX="$(PREFIX)"\
	INSTALL_BASE="$(INSTALL_BASE)"\
	PASTHRU_DEFINE='$(DEFINE) $(PASTHRU_DEFINE)'\
	PASTHRU_INC='$(INC) $(PASTHRU_INC)'


# --- MakeMaker special_targets section:
.SUFFIXES : .xs .c .C .cpp .i .s .cxx .cc $(OBJ_EXT)

.PHONY: all config static dynamic test linkext manifest blibdirs clean realclean disttest distdir pure_all subdirs clean_subdirs makemakerdflt manifypods realclean_subdirs subdirs_dynamic subdirs_pure_nolink subdirs_static subdirs-test_dynamic subdirs-test_static test_dynamic test_static



# --- MakeMaker c_o section:


# --- MakeMaker xs_c section:


# --- MakeMaker xs_o section:


# --- MakeMaker top_targets section:
all :: pure_all manifypods
	$(NOECHO) $(NOOP)

pure_all :: config pm_to_blib subdirs linkext
	$(NOECHO) $(NOOP)

	$(NOECHO) $(NOOP)

subdirs :: $(MYEXTLIB)
	$(NOECHO) $(NOOP)

config :: $(FIRST_MAKEFILE) blibdirs
	$(NOECHO) $(NOOP)

help :
	perldoc ExtUtils::MakeMaker


# --- MakeMaker blibdirs section:
blibdirs : $(INST_LIBDIR)$(DFSEP).exists $(INST_ARCHLIB)$(DFSEP).exists $(INST_AUTODIR)$(DFSEP).exists $(INST_ARCHAUTODIR)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists $(INST_SCRIPT)$(DFSEP).exists $(INST_MAN1DIR)$(DFSEP).exists $(INST_MAN3DIR)$(DFSEP).exists
	$(NOECHO) $(NOOP)

# Backwards compat with 6.18 through 6.25
blibdirs.ts : blibdirs
	$(NOECHO) $(NOOP)

$(INST_LIBDIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_LIBDIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_LIBDIR)
	$(NOECHO) $(TOUCH) $(INST_LIBDIR)$(DFSEP).exists

$(INST_ARCHLIB)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHLIB)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_ARCHLIB)
	$(NOECHO) $(TOUCH) $(INST_ARCHLIB)$(DFSEP).exists

$(INST_AUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_AUTODIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_AUTODIR)
	$(NOECHO) $(TOUCH) $(INST_AUTODIR)$(DFSEP).exists

$(INST_ARCHAUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHAUTODIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_ARCHAUTODIR)
	$(NOECHO) $(TOUCH) $(INST_ARCHAUTODIR)$(DFSEP).exists

$(INST_BIN)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_BIN)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_BIN)
	$(NOECHO) $(TOUCH) $(INST_BIN)$(DFSEP).exists

$(INST_SCRIPT)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_SCRIPT)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_SCRIPT)
	$(NOECHO) $(TOUCH) $(INST_SCRIPT)$(DFSEP).exists

$(INST_MAN1DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN1DIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_MAN1DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN1DIR)$(DFSEP).exists

$(INST_MAN3DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN3DIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_MAN3DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN3DIR)$(DFSEP).exists



# --- MakeMaker linkext section:

linkext :: dynamic
	$(NOECHO) $(NOOP)


# --- MakeMaker dlsyms section:


# --- MakeMaker dynamic_bs section:

BOOTSTRAP =


# --- MakeMaker dynamic section:

dynamic :: $(FIRST_MAKEFILE) config $(INST_BOOT) $(INST_DYNAMIC)
	$(NOECHO) $(NOOP)


# --- MakeMaker dynamic_lib section:


# --- MakeMaker static section:

## $(INST_PM) has been moved to the all: target.
## It remains here for awhile to allow for old usage: "make static"
static :: $(FIRST_MAKEFILE) $(INST_STATIC)
	$(NOECHO) $(NOOP)


# --- MakeMaker static_lib section:


# --- MakeMaker manifypods section:

POD2MAN_EXE = $(PERLRUN) "-MExtUtils::Command::MM" -e pod2man "--"
POD2MAN = $(POD2MAN_EXE)


manifypods : pure_all config  \
	lib/Font/TTF.pm \
	lib/Font/TTF/AATKern.pm \
	lib/Font/TTF/AATutils.pm \
	lib/Font/TTF/Anchor.pm \
	lib/Font/TTF/Bsln.pm \
	lib/Font/TTF/Cmap.pm \
	lib/Font/TTF/Coverage.pm \
	lib/Font/TTF/Cvt_.pm \
	lib/Font/TTF/DSIG.pm \
	lib/Font/TTF/Delta.pm \
	lib/Font/TTF/Dumper.pm \
	lib/Font/TTF/EBDT.pm \
	lib/Font/TTF/EBLC.pm \
	lib/Font/TTF/Fdsc.pm \
	lib/Font/TTF/Feat.pm \
	lib/Font/TTF/Features/Cvar.pm \
	lib/Font/TTF/Features/Size.pm \
	lib/Font/TTF/Features/Sset.pm \
	lib/Font/TTF/Fmtx.pm \
	lib/Font/TTF/Font.pm \
	lib/Font/TTF/Fpgm.pm \
	lib/Font/TTF/GDEF.pm \
	lib/Font/TTF/GPOS.pm \
	lib/Font/TTF/GSUB.pm \
	lib/Font/TTF/Glat.pm \
	lib/Font/TTF/Gloc.pm \
	lib/Font/TTF/Glyf.pm \
	lib/Font/TTF/Glyph.pm \
	lib/Font/TTF/GrFeat.pm \
	lib/Font/TTF/Hdmx.pm \
	lib/Font/TTF/Head.pm \
	lib/Font/TTF/Hhea.pm \
	lib/Font/TTF/Hmtx.pm \
	lib/Font/TTF/Kern.pm \
	lib/Font/TTF/Kern/ClassArray.pm \
	lib/Font/TTF/Kern/CompactClassArray.pm \
	lib/Font/TTF/Kern/OrderedList.pm \
	lib/Font/TTF/Kern/StateTable.pm \
	lib/Font/TTF/Kern/Subtable.pm \
	lib/Font/TTF/LTSH.pm \
	lib/Font/TTF/Loca.pm \
	lib/Font/TTF/Manual.pod \
	lib/Font/TTF/Maxp.pm \
	lib/Font/TTF/Mort.pm \
	lib/Font/TTF/Mort/Chain.pm \
	lib/Font/TTF/Mort/Contextual.pm \
	lib/Font/TTF/Mort/Insertion.pm \
	lib/Font/TTF/Mort/Ligature.pm \
	lib/Font/TTF/Mort/Noncontextual.pm \
	lib/Font/TTF/Mort/Rearrangement.pm \
	lib/Font/TTF/Mort/Subtable.pm \
	lib/Font/TTF/Name.pm \
	lib/Font/TTF/OS_2.pm \
	lib/Font/TTF/OTTags.pm \
	lib/Font/TTF/OldCmap.pm \
	lib/Font/TTF/OldMort.pm \
	lib/Font/TTF/PCLT.pm \
	lib/Font/TTF/PSNames.pm \
	lib/Font/TTF/Post.pm \
	lib/Font/TTF/Prep.pm \
	lib/Font/TTF/Prop.pm \
	lib/Font/TTF/Segarr.pm \
	lib/Font/TTF/Silf.pm \
	lib/Font/TTF/Sill.pm \
	lib/Font/TTF/Table.pm \
	lib/Font/TTF/Ttc.pm \
	lib/Font/TTF/Ttopen.pm \
	lib/Font/TTF/Useall.pm \
	lib/Font/TTF/Utils.pm \
	lib/Font/TTF/Vhea.pm \
	lib/Font/TTF/Vmtx.pm \
	lib/Font/TTF/Win32.pm \
	lib/Font/TTF/Woff.pm \
	lib/Font/TTF/Woff/MetaData.pm \
	lib/Font/TTF/Woff/PrivateData.pm \
	lib/Font/TTF/XMLparse.pm \
	lib/ttfmod.pl
	$(NOECHO) $(POD2MAN) --section=$(MAN3EXT) --perm_rw=$(PERM_RW) -u \
	  lib/Font/TTF.pm $(INST_MAN3DIR)/Font::TTF.$(MAN3EXT) \
	  lib/Font/TTF/AATKern.pm $(INST_MAN3DIR)/Font::TTF::AATKern.$(MAN3EXT) \
	  lib/Font/TTF/AATutils.pm $(INST_MAN3DIR)/Font::TTF::AATutils.$(MAN3EXT) \
	  lib/Font/TTF/Anchor.pm $(INST_MAN3DIR)/Font::TTF::Anchor.$(MAN3EXT) \
	  lib/Font/TTF/Bsln.pm $(INST_MAN3DIR)/Font::TTF::Bsln.$(MAN3EXT) \
	  lib/Font/TTF/Cmap.pm $(INST_MAN3DIR)/Font::TTF::Cmap.$(MAN3EXT) \
	  lib/Font/TTF/Coverage.pm $(INST_MAN3DIR)/Font::TTF::Coverage.$(MAN3EXT) \
	  lib/Font/TTF/Cvt_.pm $(INST_MAN3DIR)/Font::TTF::Cvt_.$(MAN3EXT) \
	  lib/Font/TTF/DSIG.pm $(INST_MAN3DIR)/Font::TTF::DSIG.$(MAN3EXT) \
	  lib/Font/TTF/Delta.pm $(INST_MAN3DIR)/Font::TTF::Delta.$(MAN3EXT) \
	  lib/Font/TTF/Dumper.pm $(INST_MAN3DIR)/Font::TTF::Dumper.$(MAN3EXT) \
	  lib/Font/TTF/EBDT.pm $(INST_MAN3DIR)/Font::TTF::EBDT.$(MAN3EXT) \
	  lib/Font/TTF/EBLC.pm $(INST_MAN3DIR)/Font::TTF::EBLC.$(MAN3EXT) \
	  lib/Font/TTF/Fdsc.pm $(INST_MAN3DIR)/Font::TTF::Fdsc.$(MAN3EXT) \
	  lib/Font/TTF/Feat.pm $(INST_MAN3DIR)/Font::TTF::Feat.$(MAN3EXT) \
	  lib/Font/TTF/Features/Cvar.pm $(INST_MAN3DIR)/Font::TTF::Features::Cvar.$(MAN3EXT) \
	  lib/Font/TTF/Features/Size.pm $(INST_MAN3DIR)/Font::TTF::Features::Size.$(MAN3EXT) \
	  lib/Font/TTF/Features/Sset.pm $(INST_MAN3DIR)/Font::TTF::Features::Sset.$(MAN3EXT) \
	  lib/Font/TTF/Fmtx.pm $(INST_MAN3DIR)/Font::TTF::Fmtx.$(MAN3EXT) \
	  lib/Font/TTF/Font.pm $(INST_MAN3DIR)/Font::TTF::Font.$(MAN3EXT) \
	  lib/Font/TTF/Fpgm.pm $(INST_MAN3DIR)/Font::TTF::Fpgm.$(MAN3EXT) \
	  lib/Font/TTF/GDEF.pm $(INST_MAN3DIR)/Font::TTF::GDEF.$(MAN3EXT) \
	  lib/Font/TTF/GPOS.pm $(INST_MAN3DIR)/Font::TTF::GPOS.$(MAN3EXT) \
	  lib/Font/TTF/GSUB.pm $(INST_MAN3DIR)/Font::TTF::GSUB.$(MAN3EXT) \
	  lib/Font/TTF/Glat.pm $(INST_MAN3DIR)/Font::TTF::Glat.$(MAN3EXT) \
	  lib/Font/TTF/Gloc.pm $(INST_MAN3DIR)/Font::TTF::Gloc.$(MAN3EXT) \
	  lib/Font/TTF/Glyf.pm $(INST_MAN3DIR)/Font::TTF::Glyf.$(MAN3EXT) \
	  lib/Font/TTF/Glyph.pm $(INST_MAN3DIR)/Font::TTF::Glyph.$(MAN3EXT) \
	  lib/Font/TTF/GrFeat.pm $(INST_MAN3DIR)/Font::TTF::GrFeat.$(MAN3EXT) \
	  lib/Font/TTF/Hdmx.pm $(INST_MAN3DIR)/Font::TTF::Hdmx.$(MAN3EXT) \
	  lib/Font/TTF/Head.pm $(INST_MAN3DIR)/Font::TTF::Head.$(MAN3EXT) \
	  lib/Font/TTF/Hhea.pm $(INST_MAN3DIR)/Font::TTF::Hhea.$(MAN3EXT) \
	  lib/Font/TTF/Hmtx.pm $(INST_MAN3DIR)/Font::TTF::Hmtx.$(MAN3EXT) \
	  lib/Font/TTF/Kern.pm $(INST_MAN3DIR)/Font::TTF::Kern.$(MAN3EXT) \
	  lib/Font/TTF/Kern/ClassArray.pm $(INST_MAN3DIR)/Font::TTF::Kern::ClassArray.$(MAN3EXT) \
	  lib/Font/TTF/Kern/CompactClassArray.pm $(INST_MAN3DIR)/Font::TTF::Kern::CompactClassArray.$(MAN3EXT) \
	  lib/Font/TTF/Kern/OrderedList.pm $(INST_MAN3DIR)/Font::TTF::Kern::OrderedList.$(MAN3EXT) \
	  lib/Font/TTF/Kern/StateTable.pm $(INST_MAN3DIR)/Font::TTF::Kern::StateTable.$(MAN3EXT) 
	$(NOECHO) $(POD2MAN) --section=$(MAN3EXT) --perm_rw=$(PERM_RW) -u \
	  lib/Font/TTF/Kern/Subtable.pm $(INST_MAN3DIR)/Font::TTF::Kern::Subtable.$(MAN3EXT) \
	  lib/Font/TTF/LTSH.pm $(INST_MAN3DIR)/Font::TTF::LTSH.$(MAN3EXT) \
	  lib/Font/TTF/Loca.pm $(INST_MAN3DIR)/Font::TTF::Loca.$(MAN3EXT) \
	  lib/Font/TTF/Manual.pod $(INST_MAN3DIR)/Font::TTF::Manual.$(MAN3EXT) \
	  lib/Font/TTF/Maxp.pm $(INST_MAN3DIR)/Font::TTF::Maxp.$(MAN3EXT) \
	  lib/Font/TTF/Mort.pm $(INST_MAN3DIR)/Font::TTF::Mort.$(MAN3EXT) \
	  lib/Font/TTF/Mort/Chain.pm $(INST_MAN3DIR)/Font::TTF::Mort::Chain.$(MAN3EXT) \
	  lib/Font/TTF/Mort/Contextual.pm $(INST_MAN3DIR)/Font::TTF::Mort::Contextual.$(MAN3EXT) \
	  lib/Font/TTF/Mort/Insertion.pm $(INST_MAN3DIR)/Font::TTF::Mort::Insertion.$(MAN3EXT) \
	  lib/Font/TTF/Mort/Ligature.pm $(INST_MAN3DIR)/Font::TTF::Mort::Ligature.$(MAN3EXT) \
	  lib/Font/TTF/Mort/Noncontextual.pm $(INST_MAN3DIR)/Font::TTF::Mort::Noncontextual.$(MAN3EXT) \
	  lib/Font/TTF/Mort/Rearrangement.pm $(INST_MAN3DIR)/Font::TTF::Mort::Rearrangement.$(MAN3EXT) \
	  lib/Font/TTF/Mort/Subtable.pm $(INST_MAN3DIR)/Font::TTF::Mort::Subtable.$(MAN3EXT) \
	  lib/Font/TTF/Name.pm $(INST_MAN3DIR)/Font::TTF::Name.$(MAN3EXT) \
	  lib/Font/TTF/OS_2.pm $(INST_MAN3DIR)/Font::TTF::OS_2.$(MAN3EXT) \
	  lib/Font/TTF/OTTags.pm $(INST_MAN3DIR)/Font::TTF::OTTags.$(MAN3EXT) \
	  lib/Font/TTF/OldCmap.pm $(INST_MAN3DIR)/Font::TTF::OldCmap.$(MAN3EXT) \
	  lib/Font/TTF/OldMort.pm $(INST_MAN3DIR)/Font::TTF::OldMort.$(MAN3EXT) \
	  lib/Font/TTF/PCLT.pm $(INST_MAN3DIR)/Font::TTF::PCLT.$(MAN3EXT) \
	  lib/Font/TTF/PSNames.pm $(INST_MAN3DIR)/Font::TTF::PSNames.$(MAN3EXT) \
	  lib/Font/TTF/Post.pm $(INST_MAN3DIR)/Font::TTF::Post.$(MAN3EXT) \
	  lib/Font/TTF/Prep.pm $(INST_MAN3DIR)/Font::TTF::Prep.$(MAN3EXT) \
	  lib/Font/TTF/Prop.pm $(INST_MAN3DIR)/Font::TTF::Prop.$(MAN3EXT) \
	  lib/Font/TTF/Segarr.pm $(INST_MAN3DIR)/Font::TTF::Segarr.$(MAN3EXT) \
	  lib/Font/TTF/Silf.pm $(INST_MAN3DIR)/Font::TTF::Silf.$(MAN3EXT) \
	  lib/Font/TTF/Sill.pm $(INST_MAN3DIR)/Font::TTF::Sill.$(MAN3EXT) \
	  lib/Font/TTF/Table.pm $(INST_MAN3DIR)/Font::TTF::Table.$(MAN3EXT) \
	  lib/Font/TTF/Ttc.pm $(INST_MAN3DIR)/Font::TTF::Ttc.$(MAN3EXT) \
	  lib/Font/TTF/Ttopen.pm $(INST_MAN3DIR)/Font::TTF::Ttopen.$(MAN3EXT) \
	  lib/Font/TTF/Useall.pm $(INST_MAN3DIR)/Font::TTF::Useall.$(MAN3EXT) \
	  lib/Font/TTF/Utils.pm $(INST_MAN3DIR)/Font::TTF::Utils.$(MAN3EXT) \
	  lib/Font/TTF/Vhea.pm $(INST_MAN3DIR)/Font::TTF::Vhea.$(MAN3EXT) \
	  lib/Font/TTF/Vmtx.pm $(INST_MAN3DIR)/Font::TTF::Vmtx.$(MAN3EXT) \
	  lib/Font/TTF/Win32.pm $(INST_MAN3DIR)/Font::TTF::Win32.$(MAN3EXT) \
	  lib/Font/TTF/Woff.pm $(INST_MAN3DIR)/Font::TTF::Woff.$(MAN3EXT) \
	  lib/Font/TTF/Woff/MetaData.pm $(INST_MAN3DIR)/Font::TTF::Woff::MetaData.$(MAN3EXT) \
	  lib/Font/TTF/Woff/PrivateData.pm $(INST_MAN3DIR)/Font::TTF::Woff::PrivateData.$(MAN3EXT) 
	$(NOECHO) $(POD2MAN) --section=$(MAN3EXT) --perm_rw=$(PERM_RW) -u \
	  lib/Font/TTF/XMLparse.pm $(INST_MAN3DIR)/Font::TTF::XMLparse.$(MAN3EXT) \
	  lib/ttfmod.pl $(INST_MAN3DIR)/ttfmod.$(MAN3EXT) 




# --- MakeMaker processPL section:


# --- MakeMaker installbin section:


# --- MakeMaker subdirs section:

# none

# --- MakeMaker clean_subdirs section:
clean_subdirs :
	$(NOECHO) $(NOOP)


# --- MakeMaker clean section:

# Delete temporary files but do not touch installed files. We don't delete
# the Makefile here so a later make realclean still has a makefile to use.

clean :: clean_subdirs
	- $(RM_F) \
	  $(BASEEXT).bso $(BASEEXT).def \
	  $(BASEEXT).exp $(BASEEXT).x \
	  $(BOOTSTRAP) $(INST_ARCHAUTODIR)/extralibs.all \
	  $(INST_ARCHAUTODIR)/extralibs.ld $(MAKE_APERL_FILE) \
	  *$(LIB_EXT) *$(OBJ_EXT) \
	  *perl.core MYMETA.json \
	  MYMETA.yml blibdirs.ts \
	  core core.*perl.*.? \
	  core.[0-9] core.[0-9][0-9] \
	  core.[0-9][0-9][0-9] core.[0-9][0-9][0-9][0-9] \
	  core.[0-9][0-9][0-9][0-9][0-9] lib$(BASEEXT).def \
	  mon.out perl \
	  perl$(EXE_EXT) perl.exe \
	  perlmain.c pm_to_blib \
	  pm_to_blib.ts so_locations \
	  tmon.out 
	- $(RM_RF) \
	  blib 
	  $(NOECHO) $(RM_F) $(MAKEFILE_OLD)
	- $(MV) $(FIRST_MAKEFILE) $(MAKEFILE_OLD) $(DEV_NULL)


# --- MakeMaker realclean_subdirs section:
# so clean is forced to complete before realclean_subdirs runs
realclean_subdirs : clean
	$(NOECHO) $(NOOP)


# --- MakeMaker realclean section:
# Delete temporary files (via clean) and also delete dist files
realclean purge :: realclean_subdirs
	- $(RM_F) \
	  $(FIRST_MAKEFILE) $(MAKEFILE_OLD) 
	- $(RM_RF) \
	  $(DISTVNAME) 


# --- MakeMaker metafile section:
metafile : create_distdir
	$(NOECHO) $(ECHO) Generating META.yml
	$(NOECHO) $(ECHO) '---' > META_new.yml
	$(NOECHO) $(ECHO) 'abstract: '\''TTF font support for Perl'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'author:' >> META_new.yml
	$(NOECHO) $(ECHO) '  - martin_hosken@sil.org' >> META_new.yml
	$(NOECHO) $(ECHO) 'build_requires:' >> META_new.yml
	$(NOECHO) $(ECHO) '  ExtUtils::MakeMaker: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'configure_requires:' >> META_new.yml
	$(NOECHO) $(ECHO) '  ExtUtils::MakeMaker: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'dynamic_config: 1' >> META_new.yml
	$(NOECHO) $(ECHO) 'generated_by: '\''ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'license: artistic_2' >> META_new.yml
	$(NOECHO) $(ECHO) 'meta-spec:' >> META_new.yml
	$(NOECHO) $(ECHO) '  url: http://module-build.sourceforge.net/META-spec-v1.4.html' >> META_new.yml
	$(NOECHO) $(ECHO) '  version: '\''1.4'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'name: Font-TTF' >> META_new.yml
	$(NOECHO) $(ECHO) 'no_index:' >> META_new.yml
	$(NOECHO) $(ECHO) '  directory:' >> META_new.yml
	$(NOECHO) $(ECHO) '    - t' >> META_new.yml
	$(NOECHO) $(ECHO) '    - inc' >> META_new.yml
	$(NOECHO) $(ECHO) 'requires:' >> META_new.yml
	$(NOECHO) $(ECHO) '  IO::String: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'version: '\''1.05'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'x_serialization_backend: '\''CPAN::Meta::YAML version 0.018'\''' >> META_new.yml
	-$(NOECHO) $(MV) META_new.yml $(DISTVNAME)/META.yml
	$(NOECHO) $(ECHO) Generating META.json
	$(NOECHO) $(ECHO) '{' > META_new.json
	$(NOECHO) $(ECHO) '   "abstract" : "TTF font support for Perl",' >> META_new.json
	$(NOECHO) $(ECHO) '   "author" : [' >> META_new.json
	$(NOECHO) $(ECHO) '      "martin_hosken@sil.org"' >> META_new.json
	$(NOECHO) $(ECHO) '   ],' >> META_new.json
	$(NOECHO) $(ECHO) '   "dynamic_config" : 1,' >> META_new.json
	$(NOECHO) $(ECHO) '   "generated_by" : "ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010",' >> META_new.json
	$(NOECHO) $(ECHO) '   "license" : [' >> META_new.json
	$(NOECHO) $(ECHO) '      "artistic_2"' >> META_new.json
	$(NOECHO) $(ECHO) '   ],' >> META_new.json
	$(NOECHO) $(ECHO) '   "meta-spec" : {' >> META_new.json
	$(NOECHO) $(ECHO) '      "url" : "http://search.cpan.org/perldoc?CPAN::Meta::Spec",' >> META_new.json
	$(NOECHO) $(ECHO) '      "version" : "2"' >> META_new.json
	$(NOECHO) $(ECHO) '   },' >> META_new.json
	$(NOECHO) $(ECHO) '   "name" : "Font-TTF",' >> META_new.json
	$(NOECHO) $(ECHO) '   "no_index" : {' >> META_new.json
	$(NOECHO) $(ECHO) '      "directory" : [' >> META_new.json
	$(NOECHO) $(ECHO) '         "t",' >> META_new.json
	$(NOECHO) $(ECHO) '         "inc"' >> META_new.json
	$(NOECHO) $(ECHO) '      ]' >> META_new.json
	$(NOECHO) $(ECHO) '   },' >> META_new.json
	$(NOECHO) $(ECHO) '   "prereqs" : {' >> META_new.json
	$(NOECHO) $(ECHO) '      "build" : {' >> META_new.json
	$(NOECHO) $(ECHO) '         "requires" : {' >> META_new.json
	$(NOECHO) $(ECHO) '            "ExtUtils::MakeMaker" : "0"' >> META_new.json
	$(NOECHO) $(ECHO) '         }' >> META_new.json
	$(NOECHO) $(ECHO) '      },' >> META_new.json
	$(NOECHO) $(ECHO) '      "configure" : {' >> META_new.json
	$(NOECHO) $(ECHO) '         "requires" : {' >> META_new.json
	$(NOECHO) $(ECHO) '            "ExtUtils::MakeMaker" : "0"' >> META_new.json
	$(NOECHO) $(ECHO) '         }' >> META_new.json
	$(NOECHO) $(ECHO) '      },' >> META_new.json
	$(NOECHO) $(ECHO) '      "runtime" : {' >> META_new.json
	$(NOECHO) $(ECHO) '         "requires" : {' >> META_new.json
	$(NOECHO) $(ECHO) '            "IO::String" : "0"' >> META_new.json
	$(NOECHO) $(ECHO) '         }' >> META_new.json
	$(NOECHO) $(ECHO) '      }' >> META_new.json
	$(NOECHO) $(ECHO) '   },' >> META_new.json
	$(NOECHO) $(ECHO) '   "release_status" : "stable",' >> META_new.json
	$(NOECHO) $(ECHO) '   "version" : "1.05",' >> META_new.json
	$(NOECHO) $(ECHO) '   "x_serialization_backend" : "JSON::PP version 2.27400_02"' >> META_new.json
	$(NOECHO) $(ECHO) '}' >> META_new.json
	-$(NOECHO) $(MV) META_new.json $(DISTVNAME)/META.json


# --- MakeMaker signature section:
signature :
	cpansign -s


# --- MakeMaker dist_basics section:
distclean :: realclean distcheck
	$(NOECHO) $(NOOP)

distcheck :
	$(PERLRUN) "-MExtUtils::Manifest=fullcheck" -e fullcheck

skipcheck :
	$(PERLRUN) "-MExtUtils::Manifest=skipcheck" -e skipcheck

manifest :
	$(PERLRUN) "-MExtUtils::Manifest=mkmanifest" -e mkmanifest

veryclean : realclean
	$(RM_F) *~ */*~ *.orig */*.orig *.bak */*.bak *.old */*.old



# --- MakeMaker dist_core section:

dist : $(DIST_DEFAULT) $(FIRST_MAKEFILE)
	$(NOECHO) $(ABSPERLRUN) -l -e 'print '\''Warning: Makefile possibly out of date with $(VERSION_FROM)'\''' \
	  -e '    if -e '\''$(VERSION_FROM)'\'' and -M '\''$(VERSION_FROM)'\'' < -M '\''$(FIRST_MAKEFILE)'\'';' --

tardist : $(DISTVNAME).tar$(SUFFIX)
	$(NOECHO) $(NOOP)

uutardist : $(DISTVNAME).tar$(SUFFIX)
	uuencode $(DISTVNAME).tar$(SUFFIX) $(DISTVNAME).tar$(SUFFIX) > $(DISTVNAME).tar$(SUFFIX)_uu
	$(NOECHO) $(ECHO) 'Created $(DISTVNAME).tar$(SUFFIX)_uu'

$(DISTVNAME).tar$(SUFFIX) : distdir
	$(PREOP)
	$(TO_UNIX)
	$(TAR) $(TARFLAGS) $(DISTVNAME).tar $(DISTVNAME)
	$(RM_RF) $(DISTVNAME)
	$(COMPRESS) $(DISTVNAME).tar
	$(NOECHO) $(ECHO) 'Created $(DISTVNAME).tar$(SUFFIX)'
	$(POSTOP)

zipdist : $(DISTVNAME).zip
	$(NOECHO) $(NOOP)

$(DISTVNAME).zip : distdir
	$(PREOP)
	$(ZIP) $(ZIPFLAGS) $(DISTVNAME).zip $(DISTVNAME)
	$(RM_RF) $(DISTVNAME)
	$(NOECHO) $(ECHO) 'Created $(DISTVNAME).zip'
	$(POSTOP)

shdist : distdir
	$(PREOP)
	$(SHAR) $(DISTVNAME) > $(DISTVNAME).shar
	$(RM_RF) $(DISTVNAME)
	$(NOECHO) $(ECHO) 'Created $(DISTVNAME).shar'
	$(POSTOP)


# --- MakeMaker distdir section:
create_distdir :
	$(RM_RF) $(DISTVNAME)
	$(PERLRUN) "-MExtUtils::Manifest=manicopy,maniread" \
		-e "manicopy(maniread(),'$(DISTVNAME)', '$(DIST_CP)');"

distdir : create_distdir distmeta 
	$(NOECHO) $(NOOP)



# --- MakeMaker dist_test section:
disttest : distdir
	cd $(DISTVNAME) && $(ABSPERLRUN) Makefile.PL "INSTALL_BASE=/home/barry/perl5" "LIB=/home/barry/Desktop/Owen_Donohue/mirdeep2/mirdeep2-master/lib/perl5"
	cd $(DISTVNAME) && $(MAKE) $(PASTHRU)
	cd $(DISTVNAME) && $(MAKE) test $(PASTHRU)



# --- MakeMaker dist_ci section:
ci :
	$(ABSPERLRUN) -MExtUtils::Manifest=maniread -e '@all = sort keys %{ maniread() };' \
	  -e 'print(qq{Executing $(CI) @all\n});' \
	  -e 'system(qq{$(CI) @all}) == 0 or die $$!;' \
	  -e 'print(qq{Executing $(RCS_LABEL) ...\n});' \
	  -e 'system(qq{$(RCS_LABEL) @all}) == 0 or die $$!;' --


# --- MakeMaker distmeta section:
distmeta : create_distdir metafile
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'exit unless -e q{META.yml};' \
	  -e 'eval { maniadd({q{META.yml} => q{Module YAML meta-data (added by MakeMaker)}}) }' \
	  -e '    or die "Could not add META.yml to MANIFEST: $${'\''@'\''}"' --
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'exit unless -f q{META.json};' \
	  -e 'eval { maniadd({q{META.json} => q{Module JSON meta-data (added by MakeMaker)}}) }' \
	  -e '    or die "Could not add META.json to MANIFEST: $${'\''@'\''}"' --



# --- MakeMaker distsignature section:
distsignature : distmeta
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'eval { maniadd({q{SIGNATURE} => q{Public-key signature (added by MakeMaker)}}) }' \
	  -e '    or die "Could not add SIGNATURE to MANIFEST: $${'\''@'\''}"' --
	$(NOECHO) cd $(DISTVNAME) && $(TOUCH) SIGNATURE
	cd $(DISTVNAME) && cpansign -s



# --- MakeMaker install section:

install :: pure_install doc_install
	$(NOECHO) $(NOOP)

install_perl :: pure_perl_install doc_perl_install
	$(NOECHO) $(NOOP)

install_site :: pure_site_install doc_site_install
	$(NOECHO) $(NOOP)

install_vendor :: pure_vendor_install doc_vendor_install
	$(NOECHO) $(NOOP)

pure_install :: pure_$(INSTALLDIRS)_install
	$(NOECHO) $(NOOP)

doc_install :: doc_$(INSTALLDIRS)_install
	$(NOECHO) $(NOOP)

pure__install : pure_site_install
	$(NOECHO) $(ECHO) INSTALLDIRS not defined, defaulting to INSTALLDIRS=site

doc__install : doc_site_install
	$(NOECHO) $(ECHO) INSTALLDIRS not defined, defaulting to INSTALLDIRS=site

pure_perl_install :: all
	$(NOECHO) umask 022; $(MOD_INSTALL) \
		"$(INST_LIB)" "$(DESTINSTALLPRIVLIB)" \
		"$(INST_ARCHLIB)" "$(DESTINSTALLARCHLIB)" \
		"$(INST_BIN)" "$(DESTINSTALLBIN)" \
		"$(INST_SCRIPT)" "$(DESTINSTALLSCRIPT)" \
		"$(INST_MAN1DIR)" "$(DESTINSTALLMAN1DIR)" \
		"$(INST_MAN3DIR)" "$(DESTINSTALLMAN3DIR)"
	$(NOECHO) $(WARN_IF_OLD_PACKLIST) \
		"$(SITEARCHEXP)/auto/$(FULLEXT)"


pure_site_install :: all
	$(NOECHO) umask 02; $(MOD_INSTALL) \
		read "$(SITEARCHEXP)/auto/$(FULLEXT)/.packlist" \
		write "$(DESTINSTALLSITEARCH)/auto/$(FULLEXT)/.packlist" \
		"$(INST_LIB)" "$(DESTINSTALLSITELIB)" \
		"$(INST_ARCHLIB)" "$(DESTINSTALLSITEARCH)" \
		"$(INST_BIN)" "$(DESTINSTALLSITEBIN)" \
		"$(INST_SCRIPT)" "$(DESTINSTALLSITESCRIPT)" \
		"$(INST_MAN1DIR)" "$(DESTINSTALLSITEMAN1DIR)" \
		"$(INST_MAN3DIR)" "$(DESTINSTALLSITEMAN3DIR)"
	$(NOECHO) $(WARN_IF_OLD_PACKLIST) \
		"$(PERL_ARCHLIB)/auto/$(FULLEXT)"

pure_vendor_install :: all
	$(NOECHO) umask 022; $(MOD_INSTALL) \
		"$(INST_LIB)" "$(DESTINSTALLVENDORLIB)" \
		"$(INST_ARCHLIB)" "$(DESTINSTALLVENDORARCH)" \
		"$(INST_BIN)" "$(DESTINSTALLVENDORBIN)" \
		"$(INST_SCRIPT)" "$(DESTINSTALLVENDORSCRIPT)" \
		"$(INST_MAN1DIR)" "$(DESTINSTALLVENDORMAN1DIR)" \
		"$(INST_MAN3DIR)" "$(DESTINSTALLVENDORMAN3DIR)"


doc_perl_install :: all

doc_site_install :: all
	$(NOECHO) $(ECHO) Appending installation info to "$(DESTINSTALLSITEARCH)/perllocal.pod"
	-$(NOECHO) umask 02; $(MKPATH) "$(DESTINSTALLSITEARCH)"
	-$(NOECHO) umask 02; $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLSITELIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> "$(DESTINSTALLSITEARCH)/perllocal.pod"

doc_vendor_install :: all


uninstall :: uninstall_from_$(INSTALLDIRS)dirs
	$(NOECHO) $(NOOP)

uninstall_from_perldirs ::

uninstall_from_sitedirs ::
	$(NOECHO) $(UNINSTALL) "$(SITEARCHEXP)/auto/$(FULLEXT)/.packlist"

uninstall_from_vendordirs ::


# --- MakeMaker force section:
# Phony target to force checking subdirectories.
FORCE :
	$(NOECHO) $(NOOP)


# --- MakeMaker perldepend section:


# --- MakeMaker makefile section:
# We take a very conservative approach here, but it's worth it.
# We move Makefile to Makefile.old here to avoid gnu make looping.
$(FIRST_MAKEFILE) : Makefile.PL $(CONFIGDEP)
	$(NOECHO) $(ECHO) "Makefile out-of-date with respect to $?"
	$(NOECHO) $(ECHO) "Cleaning current config before rebuilding Makefile..."
	-$(NOECHO) $(RM_F) $(MAKEFILE_OLD)
	-$(NOECHO) $(MV)   $(FIRST_MAKEFILE) $(MAKEFILE_OLD)
	- $(MAKE) $(USEMAKEFILE) $(MAKEFILE_OLD) clean $(DEV_NULL)
	$(PERLRUN) Makefile.PL "INSTALL_BASE=/home/barry/perl5" "LIB=/home/barry/Desktop/Owen_Donohue/mirdeep2/mirdeep2-master/lib/perl5"
	$(NOECHO) $(ECHO) "==> Your Makefile has been rebuilt. <=="
	$(NOECHO) $(ECHO) "==> Please rerun the $(MAKE) command.  <=="
	$(FALSE)



# --- MakeMaker staticmake section:

# --- MakeMaker makeaperl section ---
MAP_TARGET    = perl
FULLPERL      = "/usr/bin/perl"
MAP_PERLINC   = "-Iblib/arch" "-Iblib/lib" "-I/usr/lib/x86_64-linux-gnu/perl/5.26" "-I/usr/share/perl/5.26"

$(MAP_TARGET) :: $(MAKE_APERL_FILE)
	$(MAKE) $(USEMAKEFILE) $(MAKE_APERL_FILE) $@

$(MAKE_APERL_FILE) : static $(FIRST_MAKEFILE) pm_to_blib
	$(NOECHO) $(ECHO) Writing \"$(MAKE_APERL_FILE)\" for this $(MAP_TARGET)
	$(NOECHO) $(PERLRUNINST) \
		Makefile.PL DIR="" \
		MAKEFILE=$(MAKE_APERL_FILE) LINKTYPE=static \
		MAKEAPERL=1 NORECURS=1 CCCDLFLAGS= \
		INSTALL_BASE=/home/barry/perl5 \
		LIB=/home/barry/Desktop/Owen_Donohue/mirdeep2/mirdeep2-master/lib/perl5


# --- MakeMaker test section:
TEST_VERBOSE=0
TEST_TYPE=test_$(LINKTYPE)
TEST_FILE = test.pl
TEST_FILES = t/*.t
TESTDB_SW = -d

testdb :: testdb_$(LINKTYPE)
	$(NOECHO) $(NOOP)

test :: $(TEST_TYPE)
	$(NOECHO) $(NOOP)

# Occasionally we may face this degenerate target:
test_ : test_dynamic
	$(NOECHO) $(NOOP)

subdirs-test_dynamic :: dynamic pure_all

test_dynamic :: subdirs-test_dynamic
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness($(TEST_VERBOSE), '$(INST_LIB)', '$(INST_ARCHLIB)')" $(TEST_FILES)

testdb_dynamic :: dynamic pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) $(TESTDB_SW) "-I$(INST_LIB)" "-I$(INST_ARCHLIB)" $(TEST_FILE)

subdirs-test_static :: static pure_all

test_static :: subdirs-test_static
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness($(TEST_VERBOSE), '$(INST_LIB)', '$(INST_ARCHLIB)')" $(TEST_FILES)

testdb_static :: static pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) $(TESTDB_SW) "-I$(INST_LIB)" "-I$(INST_ARCHLIB)" $(TEST_FILE)



# --- MakeMaker ppd section:
# Creates a PPD (Perl Package Description) for a binary distribution.
ppd :
	$(NOECHO) $(ECHO) '<SOFTPKG NAME="Font-TTF" VERSION="1.05">' > Font-TTF.ppd
	$(NOECHO) $(ECHO) '    <ABSTRACT>TTF font support for Perl</ABSTRACT>' >> Font-TTF.ppd
	$(NOECHO) $(ECHO) '    <AUTHOR>martin_hosken@sil.org</AUTHOR>' >> Font-TTF.ppd
	$(NOECHO) $(ECHO) '    <IMPLEMENTATION>' >> Font-TTF.ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="IO::String" />' >> Font-TTF.ppd
	$(NOECHO) $(ECHO) '        <ARCHITECTURE NAME="x86_64-linux-gnu-thread-multi-5.26" />' >> Font-TTF.ppd
	$(NOECHO) $(ECHO) '        <CODEBASE HREF="" />' >> Font-TTF.ppd
	$(NOECHO) $(ECHO) '    </IMPLEMENTATION>' >> Font-TTF.ppd
	$(NOECHO) $(ECHO) '</SOFTPKG>' >> Font-TTF.ppd


# --- MakeMaker pm_to_blib section:

pm_to_blib : $(FIRST_MAKEFILE) $(TO_INST_PM)
	$(NOECHO) $(ABSPERLRUN) -MExtUtils::Install -e 'pm_to_blib({@ARGV}, '\''$(INST_LIB)/auto'\'', q[$(PM_FILTER)], '\''$(PERM_DIR)'\'')' -- \
	  'lib/Font/TTF.pm' 'blib/lib/Font/TTF.pm' \
	  'lib/Font/TTF/AATKern.pm' 'blib/lib/Font/TTF/AATKern.pm' \
	  'lib/Font/TTF/AATutils.pm' 'blib/lib/Font/TTF/AATutils.pm' \
	  'lib/Font/TTF/Anchor.pm' 'blib/lib/Font/TTF/Anchor.pm' \
	  'lib/Font/TTF/Bsln.pm' 'blib/lib/Font/TTF/Bsln.pm' \
	  'lib/Font/TTF/Changes_old.txt' 'blib/lib/Font/TTF/Changes_old.txt' \
	  'lib/Font/TTF/Cmap.pm' 'blib/lib/Font/TTF/Cmap.pm' \
	  'lib/Font/TTF/Coverage.pm' 'blib/lib/Font/TTF/Coverage.pm' \
	  'lib/Font/TTF/Cvt_.pm' 'blib/lib/Font/TTF/Cvt_.pm' \
	  'lib/Font/TTF/DSIG.pm' 'blib/lib/Font/TTF/DSIG.pm' \
	  'lib/Font/TTF/Delta.pm' 'blib/lib/Font/TTF/Delta.pm' \
	  'lib/Font/TTF/Dumper.pm' 'blib/lib/Font/TTF/Dumper.pm' \
	  'lib/Font/TTF/EBDT.pm' 'blib/lib/Font/TTF/EBDT.pm' \
	  'lib/Font/TTF/EBLC.pm' 'blib/lib/Font/TTF/EBLC.pm' \
	  'lib/Font/TTF/Fdsc.pm' 'blib/lib/Font/TTF/Fdsc.pm' \
	  'lib/Font/TTF/Feat.pm' 'blib/lib/Font/TTF/Feat.pm' \
	  'lib/Font/TTF/Features/Cvar.pm' 'blib/lib/Font/TTF/Features/Cvar.pm' \
	  'lib/Font/TTF/Features/Size.pm' 'blib/lib/Font/TTF/Features/Size.pm' \
	  'lib/Font/TTF/Features/Sset.pm' 'blib/lib/Font/TTF/Features/Sset.pm' \
	  'lib/Font/TTF/Fmtx.pm' 'blib/lib/Font/TTF/Fmtx.pm' \
	  'lib/Font/TTF/Font.pm' 'blib/lib/Font/TTF/Font.pm' \
	  'lib/Font/TTF/Fpgm.pm' 'blib/lib/Font/TTF/Fpgm.pm' \
	  'lib/Font/TTF/GDEF.pm' 'blib/lib/Font/TTF/GDEF.pm' \
	  'lib/Font/TTF/GPOS.pm' 'blib/lib/Font/TTF/GPOS.pm' \
	  'lib/Font/TTF/GSUB.pm' 'blib/lib/Font/TTF/GSUB.pm' \
	  'lib/Font/TTF/Glat.pm' 'blib/lib/Font/TTF/Glat.pm' \
	  'lib/Font/TTF/Gloc.pm' 'blib/lib/Font/TTF/Gloc.pm' \
	  'lib/Font/TTF/Glyf.pm' 'blib/lib/Font/TTF/Glyf.pm' \
	  'lib/Font/TTF/Glyph.pm' 'blib/lib/Font/TTF/Glyph.pm' \
	  'lib/Font/TTF/GrFeat.pm' 'blib/lib/Font/TTF/GrFeat.pm' \
	  'lib/Font/TTF/Hdmx.pm' 'blib/lib/Font/TTF/Hdmx.pm' \
	  'lib/Font/TTF/Head.pm' 'blib/lib/Font/TTF/Head.pm' \
	  'lib/Font/TTF/Hhea.pm' 'blib/lib/Font/TTF/Hhea.pm' \
	  'lib/Font/TTF/Hmtx.pm' 'blib/lib/Font/TTF/Hmtx.pm' \
	  'lib/Font/TTF/Kern.pm' 'blib/lib/Font/TTF/Kern.pm' \
	  'lib/Font/TTF/Kern/ClassArray.pm' 'blib/lib/Font/TTF/Kern/ClassArray.pm' \
	  'lib/Font/TTF/Kern/CompactClassArray.pm' 'blib/lib/Font/TTF/Kern/CompactClassArray.pm' \
	  'lib/Font/TTF/Kern/OrderedList.pm' 'blib/lib/Font/TTF/Kern/OrderedList.pm' \
	  'lib/Font/TTF/Kern/StateTable.pm' 'blib/lib/Font/TTF/Kern/StateTable.pm' \
	  'lib/Font/TTF/Kern/Subtable.pm' 'blib/lib/Font/TTF/Kern/Subtable.pm' \
	  'lib/Font/TTF/LTSH.pm' 'blib/lib/Font/TTF/LTSH.pm' \
	  'lib/Font/TTF/Loca.pm' 'blib/lib/Font/TTF/Loca.pm' \
	  'lib/Font/TTF/Manual.pod' 'blib/lib/Font/TTF/Manual.pod' \
	  'lib/Font/TTF/Maxp.pm' 'blib/lib/Font/TTF/Maxp.pm' \
	  'lib/Font/TTF/Mort.pm' 'blib/lib/Font/TTF/Mort.pm' 
	$(NOECHO) $(ABSPERLRUN) -MExtUtils::Install -e 'pm_to_blib({@ARGV}, '\''$(INST_LIB)/auto'\'', q[$(PM_FILTER)], '\''$(PERM_DIR)'\'')' -- \
	  'lib/Font/TTF/Mort/Chain.pm' 'blib/lib/Font/TTF/Mort/Chain.pm' \
	  'lib/Font/TTF/Mort/Contextual.pm' 'blib/lib/Font/TTF/Mort/Contextual.pm' \
	  'lib/Font/TTF/Mort/Insertion.pm' 'blib/lib/Font/TTF/Mort/Insertion.pm' \
	  'lib/Font/TTF/Mort/Ligature.pm' 'blib/lib/Font/TTF/Mort/Ligature.pm' \
	  'lib/Font/TTF/Mort/Noncontextual.pm' 'blib/lib/Font/TTF/Mort/Noncontextual.pm' \
	  'lib/Font/TTF/Mort/Rearrangement.pm' 'blib/lib/Font/TTF/Mort/Rearrangement.pm' \
	  'lib/Font/TTF/Mort/Subtable.pm' 'blib/lib/Font/TTF/Mort/Subtable.pm' \
	  'lib/Font/TTF/Name.pm' 'blib/lib/Font/TTF/Name.pm' \
	  'lib/Font/TTF/OS_2.pm' 'blib/lib/Font/TTF/OS_2.pm' \
	  'lib/Font/TTF/OTTags.pm' 'blib/lib/Font/TTF/OTTags.pm' \
	  'lib/Font/TTF/OldCmap.pm' 'blib/lib/Font/TTF/OldCmap.pm' \
	  'lib/Font/TTF/OldMort.pm' 'blib/lib/Font/TTF/OldMort.pm' \
	  'lib/Font/TTF/PCLT.pm' 'blib/lib/Font/TTF/PCLT.pm' \
	  'lib/Font/TTF/PSNames.pm' 'blib/lib/Font/TTF/PSNames.pm' \
	  'lib/Font/TTF/Post.pm' 'blib/lib/Font/TTF/Post.pm' \
	  'lib/Font/TTF/Prep.pm' 'blib/lib/Font/TTF/Prep.pm' \
	  'lib/Font/TTF/Prop.pm' 'blib/lib/Font/TTF/Prop.pm' \
	  'lib/Font/TTF/Segarr.pm' 'blib/lib/Font/TTF/Segarr.pm' \
	  'lib/Font/TTF/Silf.pm' 'blib/lib/Font/TTF/Silf.pm' \
	  'lib/Font/TTF/Sill.pm' 'blib/lib/Font/TTF/Sill.pm' \
	  'lib/Font/TTF/Table.pm' 'blib/lib/Font/TTF/Table.pm' \
	  'lib/Font/TTF/Ttc.pm' 'blib/lib/Font/TTF/Ttc.pm' \
	  'lib/Font/TTF/Ttopen.pm' 'blib/lib/Font/TTF/Ttopen.pm' \
	  'lib/Font/TTF/Useall.pm' 'blib/lib/Font/TTF/Useall.pm' \
	  'lib/Font/TTF/Utils.pm' 'blib/lib/Font/TTF/Utils.pm' \
	  'lib/Font/TTF/Vhea.pm' 'blib/lib/Font/TTF/Vhea.pm' \
	  'lib/Font/TTF/Vmtx.pm' 'blib/lib/Font/TTF/Vmtx.pm' \
	  'lib/Font/TTF/Win32.pm' 'blib/lib/Font/TTF/Win32.pm' \
	  'lib/Font/TTF/Woff.pm' 'blib/lib/Font/TTF/Woff.pm' \
	  'lib/Font/TTF/Woff/MetaData.pm' 'blib/lib/Font/TTF/Woff/MetaData.pm' \
	  'lib/Font/TTF/Woff/PrivateData.pm' 'blib/lib/Font/TTF/Woff/PrivateData.pm' \
	  'lib/Font/TTF/XMLparse.pm' 'blib/lib/Font/TTF/XMLparse.pm' \
	  'lib/ttfmod.pl' 'blib/lib/ttfmod.pl' 
	$(NOECHO) $(TOUCH) pm_to_blib


# --- MakeMaker selfdocument section:

# here so even if top_targets is overridden, these will still be defined
# gmake will silently still work if any are .PHONY-ed but nmake won't

static ::
	$(NOECHO) $(NOOP)

dynamic ::
	$(NOECHO) $(NOOP)

config ::
	$(NOECHO) $(NOOP)


# --- MakeMaker postamble section:
debsrc: dist
	rm -fr Font-TTF-1.05
	rm -fr libfont-ttf-perl
	rm -fr libfont-ttf-perl-1.05+
	tar xvzf Font-TTF-1.05.tar.gz
	cp -r Font-TTF-1.05 libfont-ttf-perl
	tar cvzf libfont-ttf-perl_1.05+.orig.tar.gz libfont-ttf-perl
	cp -r libfont-ttf-perl libfont-ttf-perl-1.05+
	cp -a debian libfont-ttf-perl-1.05+
	cd libfont-ttf-perl-1.05+ && dch -v 1.05+ "interim dev release" && dpkg-buildpackage -S

# make deb builds an interim deb from svn source for release
deb: deb-base
	mkdir -p dists/bionic	
	dch -D bionic -v 1.05+-1 -m -b -c libfont-ttf-perl-1.05+/debian/changelog "Auto build from perl for bionic"
	cd libfont-ttf-perl-1.05+ && pdebuild --buildresult ../dists/bionic -- --basetgz /var/cache/pbuilder/base-bionic.tgz 


# End.
